In [1]:
import pandas as pd


In [2]:
data = [ 6 , 23 , 39 , "S" , 42 ]
s = pd.Series(data)
print(s)
print(s.dtype)

0     6
1    23
2    39
3     S
4    42
dtype: object
object


In [3]:
data = [ 6 , 23 , 39  , 42 ]
s = pd.Series(data)
print(s)
print(s.dtype)

0     6
1    23
2    39
3    42
dtype: int64
int64


In [4]:
data = [ 6 , 23 , 39 , 42 ]
i = [ 'a','b','c','d']
s = pd.Series(data, index = i)
print(s)
print(s.dtype)

a     6
b    23
c    39
d    42
dtype: int64
int64


In [7]:
data = { 'v': 6 , 'M': 23 ,'S': 39 ,'A': 42 }
s = pd.Series(data)
print(s)
print(s.dtype)

v     6
M    23
S    39
A    42
dtype: int64
int64


In [9]:
data = { 'Name': ['Varun' , 'Mahesh' , 'Saiteja' , 'Anjali'],\
        'rolno' : [6 , 23 , 39  , 42 ],\
        'Clg' : ["mru", "mru" , "mru" , "mru"] }
df = pd.DataFrame(data)
print(df)


      Name  rolno  Clg
0    Varun      6  mru
1   Mahesh     23  mru
2  Saiteja     39  mru
3   Anjali     42  mru
int64


In [11]:
import numpy as np
array = np.array([[10,5,20],[14,15,16],[39,6,23]])
print(array)
df = pd.DataFrame(array)
print(df)

[[10  5 20]
 [14 15 16]
 [39  6 23]]
    0   1   2
0  10   5  20
1  14  15  16
2  39   6  23


In [21]:
Clg = pd.read_csv(r"E:\ML\semester_data.csv")
print(Clg)

       Unnamed: 0  Attendance  CGPA
0  SEM 1 , 85,8.5         NaN   NaN
1    SEM 2,90,8.8         NaN   NaN
2    SEM 3,88,8.7         NaN   NaN
3     SEM 4 ,92,9         NaN   NaN
4   SEM 5 ,87,8.6         NaN   NaN


In [16]:
import numpy as np
array=np.array([[100,950],[90,950],[80,850],[70,650],[100,950],[100,950],[100,950],[100,950]])
i=['Sem1','Sem2','Sem3','Sem4','Sem5','Sem6','Sem7','Sem8']
print(array)
df=pd.DataFrame(array,index=i,columns=["attendance","marks"])
print(df)

[[100 950]
 [ 90 950]
 [ 80 850]
 [ 70 650]
 [100 950]
 [100 950]
 [100 950]
 [100 950]]
      attendance  marks
Sem1         100    950
Sem2          90    950
Sem3          80    850
Sem4          70    650
Sem5         100    950
Sem6         100    950
Sem7         100    950
Sem8         100    950


In [22]:
iris = pd.read_csv(r"E:\ML\8836201-6f9306ad21398ea43cba4f7d537619d0e07d5ae3\iris.csv")
print(iris)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [23]:
iris.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [24]:
iris.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [26]:
print(iris.shape)
print(iris.ndim)
print(iris.size)

(150, 5)
2
750


In [27]:
iris

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [28]:
iris.iloc[20,3]

np.float64(0.2)

In [29]:
iris.iloc[10:21:]

sepal.length  sepal.width  petal.length  petal.width variety
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa

In [34]:
iris.iloc[10:21,[0,3]]




sepal.length  petal.width
10           5.4          0.2
11           4.8          0.2
12           4.8          0.1
13           4.3          0.1
14           5.8          0.2
15           5.7          0.4
16           5.4          0.4
17           5.1          0.3
18           5.7          0.3
19           5.1          0.3
20           5.4          0.2

In [33]:
iris.loc[10:21,"sepal.length":"petal.length"]

sepal.length  sepal.width  petal.length
10           5.4          3.7           1.5
11           4.8          3.4           1.6
12           4.8          3.0           1.4
13           4.3          3.0           1.1
14           5.8          4.0           1.2
15           5.7          4.4           1.5
16           5.4          3.9           1.3
17           5.1          3.5           1.4
18           5.7          3.8           1.7
19           5.1          3.8           1.5
20           5.4          3.4           1.7
21           5.1          3.7           1.5

In [36]:

iris_subset = iris.iloc[[10, 15, 20], [0, 2]]  
print(iris_subset)


    sepal.length  petal.length
10           5.4           1.5
15           5.7           1.5
20           5.4           1.7


In [41]:
data = {"Weights":[66,75,84,96,48,71,50], \
    "Heights":[156,165,186,165,174,167,150]}
bmi = pd.DataFrame(data)
bmi["BMI"] = bmi["Weights"] / ((bmi["Heights"] / 100) ** 2)
print(bmi)

   Weights  Heights        BMI
0       66      156  27.120316
1       75      165  27.548209
2       84      186  24.280264
3       96      165  35.261708
4       48      174  15.854142
5       71      167  25.458066
6       50      150  22.222222


In [48]:
bmi.loc[3] = [78,np.nan,np.nan]
bmi

Weights  Heights        BMI
0     66.0    156.0  27.120316
1     75.0    165.0  27.548209
2     84.0    186.0  24.280264
3     78.0      NaN        NaN
4     48.0    174.0  15.854142
5      NaN     65.0        NaN
6     50.0    150.0  22.222222

In [49]:
import numpy as np
bmi.loc[5] = [np.nan,65,np.nan]
bmi

Weights  Heights        BMI
0     66.0    156.0  27.120316
1     75.0    165.0  27.548209
2     84.0    186.0  24.280264
3     78.0      NaN        NaN
4     48.0    174.0  15.854142
5      NaN     65.0        NaN
6     50.0    150.0  22.222222

In [50]:
bmi.info

<bound method DataFrame.info of    Weights  Heights        BMI
0     66.0    156.0  27.120316
1     75.0    165.0  27.548209
2     84.0    186.0  24.280264
3     78.0      NaN        NaN
4     48.0    174.0  15.854142
5      NaN     65.0        NaN
6     50.0    150.0  22.222222>

In [52]:
bmi.isnull().sum()

Weights    1
Heights    1
BMI        2
dtype: int64

In [60]:
bmi["Weights"] = bmi["Weights"].fillna(65)
bmi["Heights"] = bmi["Heights"].fillna(165)
bmi

Weights  Heights        BMI     BMI_new
0     66.0    156.0  27.120316   27.120316
1     75.0    165.0  27.548209   27.548209
2     84.0    186.0  24.280264   24.280264
3     78.0     65.0        NaN  184.615385
4     48.0    174.0  15.854142   15.854142
5     65.0     65.0        NaN  153.846154
6     50.0    150.0  22.222222   22.222222

In [61]:
bmi["BMI_new"] = bmi["Weights"] / ((bmi["Heights"] / 100) ** 2)
print(bmi)

   Weights  Heights        BMI     BMI_new
0     66.0    156.0  27.120316   27.120316
1     75.0    165.0  27.548209   27.548209
2     84.0    186.0  24.280264   24.280264
3     78.0     65.0        NaN  184.615385
4     48.0    174.0  15.854142   15.854142
5     65.0     65.0        NaN  153.846154
6     50.0    150.0  22.222222   22.222222


In [11]:
#DATA VISUALIZATION ON IRIS DATASET
#import pandas as pd
#iris = pd.read_csv(r"E:\ML\8836201-6f9306ad21398ea43cba4f7d537619d0e07d5ae3\iris.csv")


In [12]:
import matplotlib.pyplot as plt
plt.hist(iris["Sepal.ength"], color="green")

ModuleNotFoundError: No module named 'matplotlib'